version: '2'
services:
  server:
    extends:
      file: ./server/docker-compose.yml
      service: web
    links:
      - client
    volumes_from:
      - client
    image: abstractmediaco/keystone-express-starter:dev
  client:
    extends:
      file: ./client/docker-compose.yml
      service: react
    image: abstractmediaco/react-redux-starter:dev
  # keystone:
  #   extends:
  #     file: ./keystone/docker-compose.yml
  #     service: keystone
  #   image: abstractmediaco/keystone
