server:
  extends:
    file: ./server/docker-compose.yml
    service: keystone
  image: abstractmediaco/keystone-container
  links:
    - client
  volumes_from:
    - client
client:
  extends:
    file: ./client/docker-compose.yml
    service: react
  image: abstractmediaco/react-redux-container
