version: '2'
services:
  web:
    build: .
    container_name: abstract_server
    env_file:
      - .env
    ports:
      - "80:5000"
      - "3001:3001"
      - "35729:35729"
    volumes:
      - .:/app/server
      - ../keystone:/app/keystone
    working_dir: /app/server
